### ISSUE TITLE
Unclear if exclude paths working correctly

### ISSUE THREAD

**Issue by kelzenberg** [vladopajic/go-test-coverage#102]
I'm trying to run the go-test-coverage but it constantly ignores my excluded paths/files.

`./.testcoverage.yml`
```yml
profile: ./cover.out
local-prefix: "broker"
threshold:
  file: 70
  package: 80
  total: 90
override:
  - threshold: 0
    path: ^.*cmd
exclude:
  paths:
    - ^.*models
```

Command
```sh
go-test-coverage --config=./.testcoverage.yml
```

Output
```sh
Files meeting coverage threshold of (70%):	FAIL

Issues with:
broker/cmd/main.go						0%
# [...] shortened for readability
::error file=broker/models/mssql/Xm.go,line=1::File test coverage below threshold of (70%)
::error ::Package (broker/models/mssql) test coverage below threshold of (80%)
# [...] shortened for readability
::error ::Total coverage below threshold of (90%)
```

As you can see, the overridden threshold for $root/cmd files is ignored and the $root/models folder is not excluded. I also tried the following exclude path regex for models:
```yml
- ^models
- ^.*models
- ^.*models/
- ^.*\/models\/
- ^broker/models
```

What am I missing here?

**Comment by vladopajic** [comment]
hey

i am not really sure what is happening here, but override and exclude rules are working correctly in all my repositories.

does `local-prefix` have same value as `module` in `go.mod` file?

in the output that you provided, `broker/models` or `^broker/models` should exclude this package. first rule is bit more relaxed, because it will exclude any file that contains `broker/models` in it's path (maybe try with this?), while second will exclude files that begins with this string. it looks to me that, for some reason, paths might not begin with `broker/models` although that's what output indicates.

to enure that rule is actually working, try excluding some specif file. for example have exclude rule with `Xm\.go$`  (i see you have this file in output provided above `broker/models/mssql/Xm.go` ).

**Comment by kelzenberg** [comment]
> does local-prefix have same value as module in go.mod file?

Yes, it does.

With `- Xm\.go$` and even `- main\.go$` excluded I still get
```sh
Issues with:
hottgenroth-data-broker/cmd/main.go							0%
::error file=hottgenroth-data-broker/models/mssql/Xm.go,line=1::File test coverage below threshold of (70%)
::error file=hottgenroth-data-broker/cmd/main.go,line=1::File test coverage below threshold of (70%)
```

I'm running `go-test-coverage --config=./.testcoverage.yml` locally, even reinstalled it globally from scratch, and I know that the lib is reading the config file because changing the profile to `./foo.out` is throwing an error. But I can't figure out why `override` and `exclude` are misbehaving...

**Comment by vladopajic** [comment]
> And maybe it's a MacOS 14.6.1 thing

i am really not sure.

if you can clone repo and run it as source `go run ./path-to-go-test-coverage/main.go --config=...` i think you can easily identify problem, and maybe open PR with a fix 💕. 

everything happens [here](https://github.com/vladopajic/go-test-coverage/blob/c7fe52e0f48e0fbed8c1812824c5346218443c70/pkg/testcoverage/coverage/cover.go#L39).

**Comment by kelzenberg** [comment]
I'll try it on a minimal repo, plus from source, and report back.
Thanks for the quick assessment 🙌

**Comment by vladopajic** [comment]
hello @kelzenberg, i would like to kindly follow up on this issue. do the exclude paths work for you?

**Comment by kelzenberg** [comment]
Hey @vladopajic, sorry for taking so much time. I tested with another colleague if its happening on an external machine (because it did on all mine) and the problem did not exist over there. In the end, I had to reinstall everything Go and now I have no issue any longer. I can't explain why though...but I guess this issue can be closed.

Thanks for the support!
